### ISSUE TITLE
Increase HAProxy version

### ISSUE THREAD

**Issue by Gladiator10864** [Kneckter/HAProxySetup#1]
HAProxy 1.8 no longer works with Ubuntu LTS 20.04. I have successfully installed HAProxy LTS 2.0 on Ubuntu 20.04 using the provided config example.

I've seen this come up several times in Discord and figured it would be worth updating the install docs to at least say `apt install haproxy=2.0.\*`

UPDATE: HAProxy no longer works somewhere between 2.0 and 2.4. HAProxy 2.4 did not work when running on Ubuntu 22.04 and 22.04 does not let you install anything less than HAProxy 2.4.

**Comment by tolukolvi** [comment]
I'd also like to know how the http_proxy option needs to be changed to make this compatible with HAProxy 2.x.

**Comment by Kneckter** [comment]
PR #2 addressed this issue.
